apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mtozyudmk-nodejs 
  janus-idp.io/tekton: mtozyudmk-nodejs
  backstage.io/kubernetes-id: mtozyudmk-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mtozyudmk-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml